name: Build and Deploy

on:
  push:
    branches:
      - main
  #repository_dispatch:
  #  types: [update_notes]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #- name: Fetch latest notes
      #  run: |
      #    git clone https://github.com/cau-dev-team/notes.git notes

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: cau-dev-team/cau-dev-team.github.io
          publish_dir: ./out
          publish_branch: main
