name: Build and Deploy

on:
  repository_dispatch:
    types: [update_notes]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest notes
        run: |
          git clone https://github.com/cau-dream-team/cau-dream-team-notes.git public/notes

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: cau-dream-team/cau-dream-team.github.io
          publish_dir: ./out
          publish_branch: main
